-- Your SQL goes here
CREATE TABLE ncch (
    id TEXT PRIMARY KEY,
    ncch_signature BYTEA NOT NULL,
    content_size INTEGER NOT NULL,
    partition_id BIGINT NOT NULL,
    maker_code SMALLINT NOT NULL,
    ncch_verson SMALLINT NOT NULL,
    program_id BIGINT NOT NULL,
    product_code BYTEA NOT NULL,
    secondary_key_slot SMALLINT NOT NULL,
    platform SMALLINT NOT NULL,
    content_is_data BOOLEAN NOT NULL,
    content_is_executable BOOLEAN NOT NULL,
    content_category SMALLINT NOT NULL,
    content_unit_size SMALLINT NOT NULL,
    fixed_key BOOLEAN NOT NULL,
    no_romfs BOOLEAN NOT NULL,
    no_crypto BOOLEAN NOT NULL,
    seed_crypto BOOLEAN NOT NULL,

    exheader_name BYTEA,
    sd_app BOOLEAN,
    remaster_version SMALLINT,
    dependencies BIGINT[48],
    save_data_size BIGINT,
    jump_id BIGINT,
    exheader_program_id BIGINT,
    core_version INTEGER,
    enable_l2_cache BOOLEAN,
    high_cpu_speed BOOLEAN,
    system_mode SMALLINT,
    n3ds_system_mode SMALLINT,
    ideal_processor SMALLINT,
    affinity_mask SMALLINT,
    thread_priority SMALLINT,
    resource_limit_desc SMALLINT[16],
    extdata_id BIGINT,
    system_savedata_id0 INTEGER,
    system_savedata_id1 INTEGER,
    storage_access_id BIGINT,
    filesystem_flag BIGINT,
    services BYTEA[34],
    resource_limit_category SMALLINT,
    kernel_desc INT[28],
    arm9_flag INT,
    arm9_flag_version SMALLINT,

    short_title SMALLINT[16][64],
    long_title SMALLINT[16][128],
    publisher SMALLINT[16][64],
    ratings SMALLINT[16],
    region_lockout INTEGER,
    match_maker_id INTEGER,
    match_maker_bit_id BIGINT,
    smdh_flags INTEGER,
    eula_version SMALLINT,
    cec_id INTEGER,
    small_icon SMALLINT[576],
    large_icon SMALLINT[2304],

    keyword TEXT NOT NULL
)
