language: rust
cache: cargo
os:
  - linux
rust:
  - stable
install:
  - cargo install cargo-web
script:
  - cargo build -p index3ds -p httpstub --release -v
  - cargo web deploy -p index3ds-frontend --release -v

env:
  global:
    - RUST_BACKTRACE=1
